name: deploy-tickets
on:
  push:
    branches:
      - master
    paths:
      - 'tickets/**'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ticketing
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && docker build -t luisarengifo/tickets .
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push luisarengifo/tickets
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment tickets-depl
