name: deploy-payments
on:
  push:
    branches:
      - master
    paths:
      - 'payments/**'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ticketing
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && docker build -t luisarengifo/payments .
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push luisarengifo/payments
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment payments-depl
